# Generated by Django 5.2.4 on 2025-07-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='dateOfJoining',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to='media/photo'),
        ),
    ]
