# Generated by Django 5.2.4 on 2025-07-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_employeemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemodel',
            name='leaveType',
            field=models.CharField(choices=[('SickLeave', 'SickLeave'), ('CasualLeave', 'CasualLeave'), ('EarnedLeave', 'EarnedLeave')], max_length=100, null=True),
        ),
    ]
