# Generated by Django 5.2.4 on 2025-07-26 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_employeemodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='approveRejectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppRej', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=100, null=True)),
                ('adminUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.leavemodel')),
            ],
        ),
    ]
