# Generated by Django 5.2.4 on 2025-07-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_approverejectmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='dateOfJoining',
            new_name='dateOfJoiemployeeModelning',
        ),
        migrations.DeleteModel(
            name='approveRejectModel',
        ),
    ]
