# Generated by Django 5.2.4 on 2025-07-26 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_employeemodel_dateofjoining_employeemodel_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
