# Generated by Django 5.2.4 on 2025-07-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_rename_dateofjoining_employeemodel_dateofjoiemployeemodelning_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='dateOfJoiemployeeModelning',
            new_name='dateOfJoining',
        ),
    ]
